### PR TITLE
Update package.json "start" script.

### PR DESCRIPTION
**Pull request by TorstenDittmann**
"open" throws error.
The error is even in the npm-debug.log of this project :)

### CODE REVIEW

**Comment by thomasconner** [comment]
It looks like `open http://localhost:3000/` only works on macOS while `start http://localhost:3000/` works on Windows. 

http://stackoverflow.com/questions/35261535/npm-scripts-start-run-express-and-open-url

**Comment by thomasconner** [comment]
@tdiddi Do you know of a solution that will work on both?

**Comment by TorstenDittmann** [comment]
I didnt know about that, it seems like its even different under Linux `xdg-open http://localhost:3000/`.

Why not simply remove the command completely and let the user open the page by hand? :)

edit: oh yeah, you found the same thread....

**Comment by thomasconner** [comment]
@tdiddi I like that idea. Can you make that change?

**Comment by thomasconner** [comment]
Thanks @tdiddi

**Comment by TorstenDittmann** [comment]
@thediycoder No problem :)

**Pull request merged**
